name: Check & Build & Test
on:
  workflow_call:
  push:
    branches:
      - avd_on_linux

jobs:
  check-commit-message:
    name: 提交日志格式化检查
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: ./.commitlintrc.yml
  check-code-format:
    name: 代码格式化检查
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Cache android-studio
        id: cache-android-studio
        uses: actions/cache@v4
        with:
          path: android-studio
          key: ${{ runner.os }}-android-studio
      - name: download android-studio
        if: steps.cache-android-studio.outputs.cache-hit != 'true'
        run: |
          wget https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2021.1.1.20/android-studio-2021.1.1.20-linux.tar.gz
          tar -xvzf android-studio-2021.1.1.20-linux.tar.gz
          rm -rf android-studio-2021.1.1.20-linux.tar.gz
      - name: use android-studio format all files
        run: ./android-studio/bin/format.sh -s .idea/codeStyles/Project.xml -r -m \*.java,\*.kt,\*.xml .
      - name: show diff for files not formated
        run: |
          if ! git diff --quiet; then
            git diff --exit-code
          fi
  build-sdk:
    needs: [ check-commit-message, check-code-format ]
    name: 构建SDK
    runs-on: ubuntu-latest
    env:
      DISABLE_TENCENT_MAVEN_MIRROR: true
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: revert gradle wrapper mirror setting
        run: echo 'distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-bin.zip' >  gradle/wrapper/gradle-wrapper.properties
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: buildSdk
        run: ./gradlew buildSdk -S
      - name: stop gradle deamon for actions/cache
        run: ./gradlew --stop
  build-sample-maven:
    needs: [ check-commit-message, check-code-format ]
    name: 构建maven依赖SDK的sample
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello world!
  build-sample-source:
    needs: build-sdk
    name: 构建源码依赖SDK的sample
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello world!
  test-sdk-on-jvm:
    needs: build-sdk
    name: JVM测试部分
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello world!
  test-sdk-on-AVD:
    needs: test-sdk-on-jvm
    name: 在AVD上测试SDK
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello world!